shop:
    resource: "@ShopBundle/Controller/"
    type:     annotation
    prefix:   /

simple_shop_app:
    resource: "@SimpleShopAppBundle/Resources/config/routing.xml"
    prefix:   /

simple_shop:
    resource: "@SimpleShopBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
